import { notFound } from "next/navigation";
import { enterSupportWorkspace, grantSuperAdmin, leaveSupportWorkspace, sendWaitlistInvite } from "@/lib/actions/support";
import { getCurrentContext } from "@/lib/current-context";
import { db } from "@/lib/db";
import { billingPeriods, clients, organizations, waitlistLeads } from "@/lib/db/schema";
import { desc } from "drizzle-orm";
import { formatDate } from "@/lib/ui";

export default async function OasisConsole({ searchParams }: { searchParams: Promise<{ invite?: string; superAdmin?: string }> }) {
  const context = await getCurrentContext();
  if (context.userRole !== "SUPER_ADMIN") notFound();
  const { invite, superAdmin } = await searchParams;
  const [workspaces, allClients, openPeriods, leads] = await Promise.all([
    db.select().from(organizations),
    db.select({ organizationId: clients.organizationId }).from(clients),
    db.select({ organizationId: billingPeriods.organizationId, status: billingPeriods.status }).from(billingPeriods),
    db.select().from(waitlistLeads).orderBy(desc(waitlistLeads.createdAt)),
  ]);

  return <main className="min-h-screen bg-[#191b1a] px-5 py-10 text-[#f1f0e9]"><div className="mx-auto max-w-5xl">
    <div className="flex flex-col justify-between gap-4 border-b border-white/10 pb-8 sm:flex-row sm:items-end"><div><p className="mono text-[9px] uppercase tracking-[.16em] text-[#d7f85b]">Oasis Console · superadmin</p><h1 className="mt-3 text-4xl font-bold tracking-[-.07em]">Control interno</h1><p className="mt-2 text-[13px] text-white/45">Adquisición, workspaces y acciones operativas.</p></div><form action={leaveSupportWorkspace}><button className="rounded-full border border-white/15 px-4 py-2.5 text-[11px] font-bold">Salir del modo soporte</button></form></div>
    {invite === "sent" && <p role="status" className="mt-5 rounded-xl border border-[#bfd866]/40 bg-[#d7f85b]/15 px-4 py-3 text-[12px] text-[#d7f85b]">Invitación enviada correctamente.</p>}
    {invite === "error" && <p role="alert" className="mt-5 rounded-xl border border-[#ffb77e]/40 bg-[#ffb77e]/10 px-4 py-3 text-[12px] text-[#ffb77e]">No se pudo enviar. Verificá que Resend esté configurado.</p>}
    {superAdmin === "granted" && <p role="status" className="mt-5 rounded-xl border border-[#bfd866]/40 bg-[#d7f85b]/15 px-4 py-3 text-[12px] text-[#d7f85b]">Superadmin asignado correctamente.</p>}
    {superAdmin === "missing" && <p role="alert" className="mt-5 rounded-xl border border-[#ffb77e]/40 bg-[#ffb77e]/10 px-4 py-3 text-[12px] text-[#ffb77e]">No encontramos un usuario de Clerk con ese email.</p>}
    {superAdmin === "invalid" && <p role="alert" className="mt-5 rounded-xl border border-[#ffb77e]/40 bg-[#ffb77e]/10 px-4 py-3 text-[12px] text-[#ffb77e]">Ingresá un email válido.</p>}
    <section className="mt-8 rounded-2xl border border-white/10 bg-white/5 p-5"><p className="mono text-[9px] uppercase tracking-[.16em] text-[#d7f85b]">Permisos de plataforma</p><h2 className="mt-2 text-2xl font-bold tracking-[-.05em]">Crear superadmin</h2><p className="mt-2 max-w-xl text-[12px] leading-5 text-white/45">Buscá un usuario ya registrado en Clerk y otorgale acceso a todos los stores. Esta acción queda auditada.</p><form action={grantSuperAdmin} className="mt-5 flex max-w-xl flex-col gap-3 sm:flex-row"><label className="sr-only" htmlFor="super-admin-email">Email del usuario</label><input id="super-admin-email" name="email" type="email" required placeholder="persona@ejemplo.com" className="min-w-0 flex-1 rounded-full border border-white/10 bg-black/20 px-4 py-3 text-[12px] text-white outline-none placeholder:text-white/30 focus:border-[#d7f85b]" /><button className="rounded-full bg-[#d7f85b] px-4 py-3 text-[11px] font-bold text-[#191b1a]">Hacer superadmin →</button></form></section>
    <section className="mt-8"><div className="flex items-end justify-between gap-4"><div><p className="mono text-[9px] uppercase tracking-[.16em] text-[#d7f85b]">Adquisición</p><h2 className="mt-2 text-2xl font-bold tracking-[-.05em]">Acceso anticipado</h2><p className="mt-2 text-[12px] text-white/45">Personas interesadas en probar Oasis.</p></div><span className="rounded-full border border-white/10 px-3 py-1.5 text-[11px] font-bold">{leads.length} leads</span></div><div className="mt-4 overflow-x-auto rounded-2xl border border-white/10"><div className="min-w-[680px]"><div className="grid grid-cols-[1.5fr_1fr_.7fr_1fr] gap-4 border-b border-white/10 bg-white/5 px-5 py-3 text-[9px] uppercase tracking-[.12em] text-white/40"><span>Email</span><span>Alta</span><span>Estado</span><span>Acción</span></div>{leads.map((lead) => <div key={lead.id} className="grid grid-cols-[1.5fr_1fr_.7fr_1fr] items-center gap-4 border-b border-white/10 px-5 py-4 text-[12px] last:border-0"><span className="font-semibold">{lead.email}</span><span className="text-white/50">{formatDate(lead.createdAt, true)}</span><span><span className={`rounded-full px-2.5 py-1 text-[9px] font-bold ${lead.status === "CONTACTED" ? "bg-[#e1dcfa] text-[#4b3d7e]" : "bg-[#d7f85b] text-[#33420d]"}`}>{lead.status === "CONTACTED" ? "Contactado" : "Nuevo"}</span></span><form action={sendWaitlistInvite}><input type="hidden" name="leadId" value={lead.id} /><button className="rounded-full bg-[#d7f85b] px-3 py-2 text-[10px] font-bold text-[#191b1a]">{lead.status === "CONTACTED" ? "Reenviar invitación" : "Enviar invitación →"}</button></form></div>)}{leads.length === 0 && <p className="px-5 py-10 text-center text-[12px] text-white/45">Todavía no hay personas en la lista.</p>}</div></div></section>
    <section className="mt-12"><p className="mono text-[9px] uppercase tracking-[.16em] text-white/40">Workspaces</p><div className="mt-4 grid gap-3">{workspaces.map((workspace) => { const count = allClients.filter((client) => client.organizationId === workspace.id).length; const open = openPeriods.filter((period) => period.organizationId === workspace.id && ["PENDING", "OVERDUE", "REJECTED"].includes(period.status)).length; return <div key={workspace.id} className="flex flex-col justify-between gap-4 rounded-2xl border border-white/10 bg-white/5 p-5 sm:flex-row sm:items-center"><div><p className="text-[15px] font-bold">{workspace.name}</p><p className="mt-1 text-[11px] text-white/45">{count} clientes · {open} cobros abiertos · {workspace.supportEmail ?? "sin email"}</p></div><form action={enterSupportWorkspace}><input type="hidden" name="organizationId" value={workspace.id} /><button className="rounded-full bg-[#d7f85b] px-4 py-2.5 text-[11px] font-bold text-[#191b1a]">Abrir panel →</button></form></div>; })}</div></section>
  </div></main>;
}
