"use client";

import { useState } from "react";
import { Icon } from "@/components/icons";
import { WaitlistForm } from "@/components/waitlist-form";

const features = [
  ["01", "Tu calendario, en orden", "Cada período nace solo. Sin planillas, sin copiar y pegar, sin olvidos.", "#d7f85b"],
  ["02", "El estado real", "Mercado Pago actualiza cada cobro. Oasis sabe quién pagó y quién necesita un empujón.", "#9f8bff"],
  ["03", "Un seguimiento humano", "Mensajes claros, a tiempo y con el tono de tu negocio. Automatizar no tiene que sonar frío.", "#ffb77e"],
];

function Logo() {
  return <a href="#top" className="flex items-center gap-2.5 text-[15px] font-extrabold tracking-[-.04em] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-acid focus-visible:ring-offset-2 focus-visible:ring-offset-ink"><span className="grid h-7 w-7 place-items-center rounded-full bg-acid text-ink"><span className="h-2 w-2 rounded-full bg-ink" /></span>oasis</a>;
}

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const focusClasses = "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-acid focus-visible:ring-offset-2 focus-visible:ring-offset-ink";
  const closeMenu = () => setMenuOpen(false);

  return (
    <main id="top" className="grain min-h-screen overflow-hidden bg-ink">
      <nav className="relative mx-auto flex max-w-[1240px] items-center justify-between border-b hairline px-5 py-5 sm:px-8 lg:px-10">
        <div className="relative z-30"><Logo /></div>
        <div className="hidden items-center gap-8 text-[12px] text-[#b6b7b0] md:flex"><a href="#como-funciona" className={`transition hover:text-paper ${focusClasses}`}>Cómo funciona</a><a href="#para-quien" className={`transition hover:text-paper ${focusClasses}`}>Para quién</a><a href="#espera" className={`transition hover:text-paper ${focusClasses}`}>Precio</a></div>
        <div className="flex items-center gap-3"><a href="/admin" className={`hidden text-[12px] text-[#b6b7b0] transition hover:text-paper sm:block ${focusClasses}`}>Iniciar sesión</a><a href="#espera" onClick={closeMenu} className={`rounded-full bg-paper px-4 py-2.5 text-[12px] font-bold text-ink transition hover:bg-acid ${focusClasses}`}>Quiero probarlo <Icon name="arrow" className="ml-1 inline h-3.5 w-3.5" /></a><button type="button" onClick={() => setMenuOpen((open) => !open)} className={`relative z-30 ml-1 grid h-9 w-9 place-items-center rounded-full border hairline transition hover:bg-paper/10 md:hidden ${focusClasses}`} aria-label={menuOpen ? "Cerrar menú" : "Abrir menú"} aria-expanded={menuOpen} aria-controls="mobile-menu"><Icon name="menu" /></button></div>
        {menuOpen && <div id="mobile-menu" className="absolute inset-x-5 top-[76px] z-20 rounded-2xl border hairline bg-[#151716] p-3 shadow-2xl md:hidden"><div className="flex flex-col gap-1 text-[13px]"><a href="#como-funciona" onClick={closeMenu} className={`rounded-xl px-4 py-3 text-[#b6b7b0] transition hover:bg-paper/10 hover:text-paper ${focusClasses}`}>Cómo funciona</a><a href="#para-quien" onClick={closeMenu} className={`rounded-xl px-4 py-3 text-[#b6b7b0] transition hover:bg-paper/10 hover:text-paper ${focusClasses}`}>Para quién</a><a href="#espera" onClick={closeMenu} className={`rounded-xl px-4 py-3 text-[#b6b7b0] transition hover:bg-paper/10 hover:text-paper ${focusClasses}`}>Precio</a><a href="/admin" onClick={closeMenu} className={`mt-2 rounded-xl bg-paper px-4 py-3 font-bold text-ink transition hover:bg-acid ${focusClasses}`}>Iniciar sesión</a></div></div>}
      </nav>

      <section className="mx-auto grid max-w-[1240px] gap-10 px-5 pb-24 pt-16 sm:px-8 sm:pt-24 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:px-10 lg:pb-32 lg:pt-28">
        <div className="reveal relative z-10"><div className="mono mb-7 flex items-center gap-3 text-[10px] uppercase tracking-[.18em] text-acid"><span className="h-1.5 w-1.5 rounded-full bg-acid shadow-[0_0_14px_#d7f85b]" />La calma de cobrar a tiempo</div><h1 className="display max-w-[720px] text-[clamp(4.3rem,10vw,8.7rem)] font-semibold">Cobros que<br /><span className="text-acid">se ordenan</span><br />solos.</h1><p className="mt-8 max-w-[430px] text-[16px] leading-7 text-[#a9aaa3]">Oasis conecta tus servicios con tus pagos. Para que sepas qué está al día, qué falta y cuándo hacer seguimiento.</p><div className="mt-9 flex flex-wrap items-center gap-5"><a href="#espera" className="group rounded-full bg-acid px-5 py-3.5 text-[13px] font-bold text-ink transition hover:bg-[#e6ff87]">Empezar ahora <Icon name="arrow" className="ml-4 inline h-4 w-4 transition group-hover:translate-x-1" /></a><a href="#como-funciona" className="text-[13px] text-[#b6b7b0] hover:text-paper"><Icon name="play" className="mr-2 inline h-3.5 w-3.5" /> Ver cómo funciona</a></div></div>
        <div className="reveal relative mx-auto h-[390px] w-full max-w-[540px] lg:h-[510px]" style={{ animationDelay: ".12s" }}><div className="wave absolute inset-0 rounded-[2rem] border hairline shadow-2xl"><div className="absolute left-6 top-6 z-10 flex items-center gap-2 mono text-[9px] uppercase tracking-[.16em] text-[#a9aaa3]"><span className="h-1.5 w-1.5 rounded-full bg-acid" /> live overview</div><div className="absolute bottom-6 left-6 z-10"><p className="mono text-[10px] uppercase tracking-[.15em] text-[#85877f]">Cobrado este mes</p><p className="display mt-2 text-5xl font-semibold text-paper">$248.400</p></div><div className="absolute right-6 top-6 z-10 rounded-full border border-acid/30 bg-acid/10 px-3 py-1.5 mono text-[9px] text-acid">+18.4%</div></div><div className="absolute -bottom-5 -left-2 z-20 rounded-2xl border hairline bg-[#151716]/95 p-4 backdrop-blur-xl sm:-left-8"><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-acid/15 text-acid"><Icon name="check" /></span><div><p className="text-[12px] font-bold">3 pagos confirmados</p><p className="mono mt-1 text-[9px] text-[#85877f]">hace menos de 1 min</p></div></div></div></div>
      </section>

      <div className="mx-auto max-w-[1240px] border-t hairline px-5 sm:px-8 lg:px-10"><div className="flex flex-wrap items-center justify-between gap-5 py-6"><p className="mono text-[10px] uppercase tracking-[.14em] text-[#6f716b]">Para quienes cobran por su tiempo</p><div className="flex flex-wrap gap-x-7 gap-y-2 text-[13px] text-[#777970]"><span>entrenadores</span><span>contadores</span><span>consultores</span><span>profesores</span><span>freelancers</span></div></div></div>

      <section id="como-funciona" className="scroll-mt-8 mx-auto max-w-[1240px] px-5 py-28 sm:px-8 lg:px-10 lg:py-36"><div className="mb-14 grid gap-6 md:grid-cols-[.8fr_1.2fr] md:items-end"><p className="mono text-[10px] uppercase tracking-[.18em] text-acid">/ El sistema</p><h2 className="display max-w-[680px] text-5xl font-semibold sm:text-7xl">Menos perseguir.<br /><span className="text-[#666861]">Más trabajar.</span></h2></div><div className="grid border-t hairline md:grid-cols-3">{features.map(([num, title, text, color]) => <div key={num} className="border-b hairline py-7 md:border-b-0 md:border-r md:px-7 md:py-8 first:md:pl-0 last:md:border-r-0"><div className="flex items-center justify-between"><span className="mono text-[10px] text-[#6f716b]">{num}</span><span className="h-2 w-2 rounded-full" style={{ backgroundColor: color }} /></div><h3 className="mt-14 text-xl font-semibold tracking-[-.04em]">{title}</h3><p className="mt-4 max-w-[280px] text-[14px] leading-6 text-[#888a83]">{text}</p></div>)}</div></section>

      <section id="para-quien" className="scroll-mt-8 border-y hairline bg-[#111312]"><div className="mx-auto grid max-w-[1240px] gap-12 px-5 py-24 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:px-10 lg:py-32"><div><p className="mono text-[10px] uppercase tracking-[.18em] text-violet">/ Diseñado para crecer</p><h2 className="display mt-7 text-5xl font-semibold sm:text-6xl">Tu negocio<br />también merece<br /><span className="text-violet">un respiro.</span></h2></div><div className="self-end"><p className="max-w-[450px] text-[17px] leading-8 text-[#aaaBA4]">Oasis se conecta con tu cuenta de Mercado Pago y convierte cada transferencia en una respuesta clara. El dinero va a vos. El orden también.</p><div className="mt-10 grid max-w-[500px] gap-3 sm:grid-cols-2"><div className="rounded-2xl border hairline p-5"><Icon name="dollar" className="h-5 w-5 text-acid" /><p className="mt-8 text-[13px] font-semibold">Tu cuenta, tus fondos</p><p className="mt-2 text-[12px] leading-5 text-[#777970]">Nunca tocamos tu dinero.</p></div><div className="rounded-2xl border hairline p-5"><Icon name="sparkle" className="h-5 w-5 text-violet" /><p className="mt-8 text-[13px] font-semibold">Automático de verdad</p><p className="mt-2 text-[12px] leading-5 text-[#777970]">El estado se actualiza solo.</p></div></div></div></div></section>

      <section id="espera" className="scroll-mt-8 mx-auto max-w-[1240px] px-5 py-28 sm:px-8 lg:px-10 lg:py-36"><div className="relative overflow-hidden rounded-[2rem] border border-acid/30 bg-acid p-7 text-ink sm:p-12 lg:p-16"><div className="absolute -right-16 -top-28 h-80 w-80 rounded-full border-[1px] border-ink/20 opacity-50" /><div className="absolute -right-2 -top-16 h-64 w-64 rounded-full border-[1px] border-ink/20 opacity-50" /><div className="relative max-w-[680px]"><p className="mono text-[10px] uppercase tracking-[.18em] opacity-60">/ Acceso anticipado</p><h2 className="display mt-7 text-5xl font-semibold sm:text-7xl">Cobrar bien<br />se siente bien.</h2><p className="mt-6 max-w-[400px] text-[15px] leading-6 text-ink/70">Estamos preparando Oasis para profesionales que quieren dejar de perseguir pagos.</p><WaitlistForm /></div></div></section>

      <footer className="mx-auto flex max-w-[1240px] flex-col gap-5 border-t hairline px-5 py-8 sm:flex-row sm:items-center sm:justify-between sm:px-8 lg:px-10"><Logo /><div className="flex items-center gap-5 text-[11px] text-[#777970]"><a href="#como-funciona" className={focusClasses}>Producto</a><a href="mailto:soporte@oasis.app" className={focusClasses}>Contacto</a><span>© 2026 Oasis</span></div></footer>
    </main>
  );
}
