import { and, eq } from "drizzle-orm";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin-shell";
import { updateServicePlan } from "@/lib/actions/service-plans";
import { getCurrentContext } from "@/lib/current-context";
import { db } from "@/lib/db";
import { servicePlans } from "@/lib/db/schema";

const input = "mt-2 w-full rounded-xl border border-black/10 bg-[#f1f0e9] px-4 py-3 text-[13px] outline-none focus:border-[#191b1a]";
export default async function EditarPlan({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const context = await getCurrentContext(); const [plan] = await db.select().from(servicePlans).where(and(eq(servicePlans.id, id), eq(servicePlans.organizationId, context.organizationId))).limit(1); if (!plan) notFound(); return <AdminShell><div className="mx-auto max-w-[850px] px-5 py-8 sm:px-8"><a href="/admin/planes" className="text-[12px] font-semibold text-black/50">← Volver a planes</a><div className="mt-8"><p className="mono text-[9px] uppercase tracking-[.16em] text-black/40">Catálogo · edición global</p><h2 className="mt-3 text-4xl font-bold tracking-[-.07em]">{plan.name}</h2><p className="mt-2 text-[13px] text-black/45">El nuevo precio se aplica a los cobros futuros de todos los clientes asignados.</p></div><form action={updateServicePlan} className="mt-8 rounded-2xl border border-black/10 bg-[#e8e7df] p-5 sm:p-7"><input type="hidden" name="id" value={plan.id} /><div className="grid gap-4 sm:grid-cols-2"><Field label="Nombre del plan" name="name" required defaultValue={plan.name} className="sm:col-span-2" /><Field label="Descripción" name="description" defaultValue={plan.description ?? ""} className="sm:col-span-2" /><Field label="Precio" name="amount" required inputMode="decimal" defaultValue={String(plan.amount / 100)} /><label className="text-[12px] font-semibold">Moneda<select name="currency" className={input} defaultValue="ARS"><option value="ARS">Pesos argentinos (ARS)</option></select></label><label className="text-[12px] font-semibold">Frecuencia<select name="frequency" className={input} defaultValue={plan.frequency === "CUSTOM" ? "MONTHLY" : plan.frequency}><option value="WEEKLY">Semanal</option><option value="BIWEEKLY">Cada 15 días</option><option value="MONTHLY">Mensual</option></select></label><Field label="Día de vencimiento" name="dueDay" type="number" min="0" max="31" defaultValue={String(plan.dueDay ?? 10)} /></div><div className="mt-7 flex justify-end gap-2"><a href="/admin/planes" className="rounded-full border border-black/10 px-5 py-3 text-[12px] font-semibold">Cancelar</a><button className="rounded-full bg-[#191b1a] px-5 py-3 text-[12px] font-bold text-white">Actualizar para todos →</button></div></form></div></AdminShell>; }
function Field({ label, className = "", ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string; className?: string }) { return <label className={`text-[12px] font-semibold ${className}`}>{label}<input className={input} {...props} /></label>; }
