import { and, eq } from "drizzle-orm";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin-shell";
import { PaymentLinkActions } from "@/components/payment-link-actions";
import { generatePaymentLink } from "@/lib/actions/payments";
import { getCurrentContext } from "@/lib/current-context";
import { db } from "@/lib/db";
import { billingPeriods, billingPlans, clients, paymentConnections, payments } from "@/lib/db/schema";
import { formatMoney } from "@/lib/money";
import { mercadoPagoPaymentUrl } from "@/lib/payments/mercado-pago";
import { formatDate, frequencyLabel, initials, paymentStatus, periodLabel } from "@/lib/ui";

export default async function CobroDetalle({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ link?: string }> }) {
  const [{ id }, { link: linkResult }] = await Promise.all([params, searchParams]);
  const context = await getCurrentContext();
  const [[period], [payment], [connection]] = await Promise.all([
    db.select({ id: billingPeriods.id, organizationId: billingPeriods.organizationId, clientId: clients.id, clientName: clients.name, clientEmail: clients.email, clientPhone: clients.phone, planName: billingPlans.serviceName, frequency: billingPlans.frequency, dueDay: billingPlans.dueDay, intervalDays: billingPlans.intervalDays, dueAt: billingPeriods.dueAt, amount: billingPeriods.amount, currency: billingPeriods.currency, status: billingPeriods.status, paidAt: billingPeriods.paidAt, paymentLink: billingPeriods.paymentLink, createdAt: billingPeriods.createdAt }).from(billingPeriods).innerJoin(clients, eq(clients.id, billingPeriods.clientId)).innerJoin(billingPlans, eq(billingPlans.id, billingPeriods.planId)).where(and(eq(billingPeriods.id, id), eq(billingPeriods.organizationId, context.organizationId))).limit(1),
    db.select().from(payments).where(eq(payments.billingPeriodId, id)).limit(1),
    db.select({ status: paymentConnections.status }).from(paymentConnections).where(and(eq(paymentConnections.organizationId, context.organizationId), eq(paymentConnections.provider, "MERCADO_PAGO"))).limit(1),
  ]);
  if (!period) notFound();
  const state = paymentStatus[period.status];
  const connected = connection?.status === "CONNECTED";
  const canGenerateLink = ["PENDING", "IN_PROCESS", "OVERDUE", "REJECTED"].includes(period.status);
  const confirmationLabel = payment?.provider.replaceAll("_", " ") ?? (period.status === "APPROVED" ? "Pago confirmado" : "Esperando proveedor");
  const whatsappMessage = period.paymentLink
    ? `Hola ${period.clientName}, te comparto el link para abonar ${period.planName}, correspondiente a ${periodLabel(period.dueAt)}.\n\nImporte: ${formatMoney(period.amount, period.currency)}\nVencimiento: ${formatDate(period.dueAt, true)}\n\n${period.paymentLink}`
    : "";

  return <AdminShell><div className="mx-auto max-w-[1000px] px-5 py-8 sm:px-8"><a href="/admin/cobros" className="text-[12px] font-semibold text-black/50 hover:text-black">← Volver a cobros</a><div className="mt-8 flex flex-col justify-between gap-5 border-b border-black/10 pb-8 sm:flex-row sm:items-end"><div><p className="mono text-[9px] uppercase tracking-[.16em] text-black/40">Detalle del cobro</p><h2 className="mt-3 text-3xl font-bold tracking-[-.07em] sm:text-4xl">{periodLabel(period.dueAt)} · {period.clientName}</h2><p className="mt-2 text-[13px] text-black/45">Generado automáticamente por el plan del cliente</p></div><span className={`inline-flex w-fit rounded-full border px-3 py-1.5 text-[11px] font-bold ${state.tone}`}>{state.label}</span></div>
    <div className="mt-8 grid gap-4 lg:grid-cols-[1.25fr_.75fr]"><section className="rounded-2xl bg-[#191b1a] p-6 text-[#f1f0e9] sm:p-8"><p className="mono text-[9px] uppercase tracking-[.16em] text-white/45">Monto del cobro</p><p className="mt-5 text-5xl font-bold tracking-[-.07em]">{formatMoney(period.amount, period.currency)}</p><div className="mt-10 grid gap-5 border-t border-white/10 pt-5 sm:grid-cols-2"><div><p className="text-[10px] text-white/45">Vencimiento</p><p className="mt-1 text-[13px] font-semibold">{formatDate(period.dueAt, true)}</p></div><div><p className="text-[10px] text-white/45">Confirmación</p><p className="mt-1 text-[13px] font-semibold">{confirmationLabel}</p></div></div></section><section className="rounded-2xl border border-black/10 bg-[#e8e7df] p-6 sm:p-8"><p className="mono text-[9px] uppercase tracking-[.16em] text-black/40">Plan asociado</p><h3 className="mt-5 text-xl font-bold tracking-[-.05em]">{period.planName}</h3><p className="mt-2 text-[13px] text-black/50">{frequencyLabel(period.frequency, period.dueDay, period.intervalDays)}</p></section></div>
    <section className="mt-4 overflow-hidden rounded-2xl border border-black/10 bg-[#d7f85b]"><div className="grid gap-6 p-6 sm:p-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="mono text-[9px] uppercase tracking-[.16em] text-[#4e6218]">Link de pago</p><h3 className="mt-4 text-2xl font-bold tracking-[-.06em]">{period.paymentLink ? "Listo para compartir" : canGenerateLink ? "Generá un link de pago" : "Este cobro ya no necesita un link"}</h3><p className="mt-2 max-w-[590px] text-[12px] leading-5 text-black/55">{period.paymentLink ? "Enviás el link por WhatsApp y Oasis actualiza el estado automáticamente cuando Mercado Pago confirma el pago." : canGenerateLink ? "Creamos un link de pago único para este cobro. El dinero se acredita en la cuenta de Mercado Pago conectada." : "Los links solo se generan para cobros pendientes, vencidos o rechazados."}</p>{period.paymentLink ? <p className="mono mt-5 max-w-[620px] truncate rounded-lg border border-black/10 bg-white/35 px-3 py-2 text-[10px] text-black/55">{period.paymentLink}</p> : null}{linkResult === "error" ? <p className="mt-4 rounded-lg border border-[#bd5668] bg-[#ffd5dc] px-3 py-2 text-[11px] font-semibold text-[#762332]">Mercado Pago no pudo generar el link. Revisá la conexión e intentá nuevamente.</p> : null}{linkResult === "created" ? <p className="mt-4 text-[11px] font-bold text-[#33420d]">Link generado correctamente ✓</p> : null}</div><div>{period.paymentLink ? <PaymentLinkActions url={period.paymentLink} message={whatsappMessage} phone={period.clientPhone} /> : canGenerateLink && connected ? <form action={generatePaymentLink}><input type="hidden" name="periodId" value={period.id} /><button className="rounded-full bg-[#191b1a] px-5 py-3 text-[11px] font-bold text-[#f1f0e9] transition hover:bg-black">Generar link de cobro →</button></form> : canGenerateLink ? <a href="/admin/preferencias" className="inline-flex rounded-full bg-[#191b1a] px-5 py-3 text-[11px] font-bold text-[#f1f0e9]">Conectar Mercado Pago →</a> : null}</div></div></section>
    <div className="mt-4 grid gap-4 lg:grid-cols-2"><a href={`/admin/clientes/${period.clientId}`} className="rounded-2xl border border-black/10 bg-[#e8e7df] p-6 transition hover:bg-[#deddd5]"><p className="mono text-[9px] uppercase tracking-[.16em] text-black/40">Cliente</p><div className="mt-5 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#9f8bff] text-[11px] font-bold">{initials(period.clientName)}</span><div><p className="text-[14px] font-bold">{period.clientName}</p><p className="mt-1 text-[11px] text-black/45">{period.clientEmail ?? "Ver ficha del cliente"} →</p></div></div></a><section className="rounded-2xl border border-black/10 bg-[#e8e7df] p-6"><p className="mono text-[9px] uppercase tracking-[.16em] text-black/40">Actividad</p><div className="mt-5 space-y-4 text-[12px]"><div className="flex justify-between border-b border-black/10 pb-3"><span className="text-black/50">Cobro creado</span><span>{formatDate(period.createdAt)}</span></div><div className="flex justify-between"><span className="text-black/50">Último estado</span><span>{period.paidAt ? `Confirmado ${formatDate(period.paidAt)}` : state.label}</span></div></div></section></div>
    {payment && period.status === "APPROVED" ? <section className="mt-4 rounded-2xl border border-[#bfd866] bg-[#e1f39a] p-6 sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><p className="mono text-[9px] uppercase tracking-[.16em] text-[#4e6218]">Comprobante de Mercado Pago</p><h3 className="mt-4 text-2xl font-bold tracking-[-.06em]">Confirmado en Mercado Pago</h3><p className="mt-2 max-w-[560px] text-[12px] leading-5 text-black/55">Mercado Pago confirmó este cobro. Consultá el detalle de la operación directamente en tu cuenta de Mercado Pago.</p></div><a href={mercadoPagoPaymentUrl(payment.providerPaymentId)} target="_blank" rel="noreferrer" className="inline-flex shrink-0 items-center justify-center rounded-full bg-[#191b1a] px-4 py-3 text-[11px] font-bold text-[#f1f0e9] transition hover:bg-black">Ver en Mercado Pago ↗</a></div><div className="mt-7 grid gap-4 border-t border-black/10 pt-5 sm:grid-cols-3"><div><p className="text-[10px] text-black/45">Número de operación</p><p className="mono mt-1 truncate text-[11px] font-medium" title={payment.providerPaymentId}>{payment.providerPaymentId}</p></div><div><p className="text-[10px] text-black/45">Importe confirmado</p><p className="mt-1 text-[12px] font-semibold">{formatMoney(payment.amount, payment.currency)}</p></div><div><p className="text-[10px] text-black/45">Fecha de aprobación</p><p className="mt-1 text-[12px] font-semibold">{payment.paidAt ? formatDate(payment.paidAt, true) : "—"}</p></div></div></section> : null}
  </div></AdminShell>;
}
